version: '3.6'

services:
  custompios:
    image: guysoft/custompios:devel
    container_name: mainsailos-build
    tty: true
    restart: never
    privileged: true
    volumes:
      - ./src:/distro
    devices:
      - /dev/loop-control
