#!/usr/bin/env bash
# LED Effects for Klipper
# Script that installs the LED Effects for Klipper plugin
# Written by Morton Jonuschat
# GPL V3
########

# Source error handling, leave this in place
set -xe

# Source CustomPIOS common.sh
source /common.sh
install_cleanup_trap

# make sure that this module can be used standalone
apt_update_skip

check_install_pkgs "git"

## Installing KlipperScreen
echo_green "Installing LED Effects for Klipper plugin"
pushd "/home/${BASE_USER}" &>/dev/null || exit 1
gitclone LED_EFFECT_REPO klipper_led_effect

ln -sf "/home/${BASE_USER}/klipper_led_effect/src/led_effect.py" \
    "/home/${BASE_USER}/klipper/klippy/extras/led_effect.py"

## Unpack the filesystem
unpack "/filesystem/home/${BASE_USER}" "/home/${BASE_USER}" "${BASE_USER}"


## Configure automatic updates
if [ "${LED_EFFECT_UPDATE_MANAGER_ENABLED}" == "yes" ]; then
    sed -i -E -e "s#@@@ORIGIN@@@#${LED_EFFECT_REPO_SHIP}###g" "/home/${BASE_USER}/printer_data/config/moonraker.d/update_manager/led_effect.conf"
else
    rm -f "/home/${BASE_USER}/printer_data/config/moonraker.d/update_manager/led_effect.conf"
fi

# Installation complete
popd || exit 1
